import { WorksSection } from "../../components/ui";
import imageDimsJson from "./imageManifest.json";

/**
 * 480px-wide thumbnails (imageKey → URL) for the carousel, gallery and
 * showcase. The key comes from the thumb filename (baseName without extension).
 */
const thumbModules = import.meta.glob("../../assets/img/works/**/thumbs/*.webp", {
  eager: true,
  query: "?url",
  import: "default",
}) as Record<string, string>;

const thumbMap: Record<string, string> = {};
for (const [path, url] of Object.entries(thumbModules)) {
  const key = path.slice(path.lastIndexOf("/") + 1, path.lastIndexOf("."));
  thumbMap[key] = url;
}

/**
 * Build-time dimensions (imageKey → { w, h }) for the album assets, so the
 * Masonry can pack columns by aspect ratio without downloading the
 * full-resolution images first. Generated by `scripts/generate-image-manifest.mjs`.
 */
const imageDims: Record<string, { w: number; h: number }> = imageDimsJson;

export function Works() {
  return <WorksSection thumbMap={thumbMap} imageDims={imageDims} />;
}