export * from './AboutUs/About';
export * from './Contact/Contact';
export * from './Faq/Faq';
export * from '../components/layout/Footer';
export * from '../components/layout/Header';
export * from '../components/layout/Hero';
export * from './Home/Home';
export * from '../components/layout/Reviews';
export * from './Services/Services';
